namespace PC_APP
{
	[default_interface]
	runtimeclass Scenario1_Discovery : Windows.UI.Xaml.Controls.Page
	{
		Scenario1_Discovery();

		Windows.Foundation.Collections.IObservableVector<Object> KnownDevices{ get; };

		Windows.UI.Xaml.Controls.ListView ResultsListView{ get; };
		void ActionButton_Click();
		void ConnectButton_Click();
		void DisconnectButton_Click();
		Boolean Not(Boolean value);
	};

	[default_interface]
	runtimeclass Scenario2_Connect : Windows.UI.Xaml.Controls.Page
	{
		Scenario2_Connect();

		void ConnectButton_Click();
		void ServiceList_SelectionChanged();
		void CharacteristicList_SelectionChanged();
		void CharacteristicReadButton_Click();
		void CharacteristicWriteButton_Click();
		void CharacteristicWriteButtonInt_Click();
		void ValueChangedSubscribeToggle_Click();

		void LockButton_Click();
		void UnlockButton_Click();
		void TestButton_Click();

		void DisConnectButton_Click();
	};

	/// <summary>
	///     Display class used to represent a BluetoothLEDevice in the Device list
	/// </summary>
	runtimeclass BluetoothLEDeviceDisplay : Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		Windows.Devices.Enumeration.DeviceInformation DeviceInformation{ get; };

		String Id{ get; };
		String Name{ get; };
		Boolean IsPaired{ get; };
		Boolean IsConnected{ get; };
		Boolean IsConnectable{ get; };

		IMapView<String, Object> Properties{ get; };

		Windows.UI.Xaml.Media.Imaging.BitmapImage GlyphBitmapImage{ get; };

		void Update(Windows.Devices.Enumeration.DeviceInformationUpdate deviceInfoUpdate);
	};
}
